note: ttttest
url: https://hclsofy.com/sofy/catalog/hcl-devops?selectedaction=launchit
icon: https://s2.googleusercontent.com/s2/favicons?sz=48&domain_url=https://hclsofy.com/sofy/catalog/hcl-devops
type: web
